[package]
name = "vts"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
candid = { version = "0.10.7", features = [], default-features = false }
ic-cdk = { version = "0.13.2", features = [], default-features = false }
ic-stable-structures = { version = "0.6.4", features = [], default-features = false }
serde = { version = "1.0.200", features = [], default-features = false }

[dev-dependencies]
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"], default-features = false }
ic-agent = { version = "0.34.0", features = [], default-features = true }
serde_json = { version = "1.0.116", features = [], default-features = false }
