export const FirmwaresRouteName = 'firmwares'
export const AgreementFirmwaresRouteName = 'agreementFirmwares'
export const AgreementsRouteName = 'agreements'
export const VehicleLinkRouteName = 'vehicleLink'
export const CreateAgreementRouteName = 'createAgreement'
