[package]
name = "firmware"
version = "0.1.0"
edition = "2021"

[dependencies]
vts = { path = "../canisters/src/vts", features = [], default-features = false }
bincode = { workspace = true }
ic-agent = { workspace = true }
k256 = { workspace = true }
rand = { workspace = true }
