[package]
name = "firmware"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-agent = { version = "0.36.0", features = [], default-features = true }
k256 = { version = "0.13.3", features = [], default-features = false }
